In [ ]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = 'D:\projects\projects-python\projects\LOL\player_statistics_cleaned_final.csv'

df = pd.read_csv(file_path)

In [4]:
df.head()

,TeamName,PlayerName,Position,Games,Win rate,KDA,Avg kills,Avg deaths,Avg assists,CSPerMin,...,Avg VWPM,GD@15,CSD@15,XPD@15,FB %,FB Victim,Penta Kills,Solo Kills,Country,FlashKeybind
0,Top Esports,369,Top,8,0.500,3.1,2.5,2.4,4.9,7.6,...,0.13,322,5,424,0.000,0.25,0,2,China,D
1,Dplus KIA,aiming,Adc,9,0.333,4.8,5.0,2.0,4.7,10.1,...,0.10,-112,1,97,0.333,0.00,0,2,South Korea,F
2,MAD Lions KOI,alvaro,Support,5,0.200,1.5,0.2,4.4,6.2,1.2,...,0.49,-3,2,-256,0.000,0.60,0,-,Spain,D
3,Team Liquid,apa,Mid,10,0.500,2.4,3.5,3.2,4.2,8.7,...,0.18,278,2,216,0.400,0.00,0,3,United States,D
4,PSG Talon,azhi,Top,5,0.200,2.3,2.2,3.0,4.8,7.5,...,0.18,-311,-10,-168,0.200,0.00,0,-,Taiwan,D

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TeamName       81 non-null     object
 1   PlayerName     81 non-null     object
 2   Position       81 non-null     object
 3   Games          81 non-null     int64
 4   Win rate       81 non-null     float64
 5   KDA            81 non-null     float64
 6   Avg kills      81 non-null     float64
 7   Avg deaths     81 non-null     float64
 8   Avg assists    81 non-null     float64
 9   CSPerMin       81 non-null     float64
 10  GoldPerMin     81 non-null     int64
 11  KP%            81 non-null     float64
 12  DamagePercent  81 non-null     float64
 13  DPM            81 non-null     int64
 14  VSPM           81 non-null     float64
 15  Avg WPM        81 non-null     float64
 16  Avg WCPM       81 non-null     float64
 17  Avg VWPM       81 non-null     float64
 18  GD@15          81 non-null     int64
 19  CSD@15         81 non-null     int64
 20  XPD@15         81 non-null     int64
 21  FB %           81 non-null     float64
 22  FB Victim      81 non-null     float64
 23  Penta Kills    81 non-null     int64
 24  Solo Kills     81 non-null     object
 25  Country        81 non-null     object
 26  FlashKeybind   81 non-null     object
dtypes: float64(14), int64(7), object(6)
memory usage: 17.2+ KB

In [21]:
df.describe()

,Games,Win rate,KDA,Avg kills,Avg deaths,Avg assists,CSPerMin,GoldPerMin,KP%,DamagePercent,...,VSPM,Avg WPM,Avg WCPM,Avg VWPM,GD@15,CSD@15,XPD@15,FB %,FB Victim,Penta Kills
count,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.00000,81.000000,81.000000,81.000000,...,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.0
mean,8.641975,0.455975,3.765432,2.686420,2.875309,6.755556,6.65679,362.654321,0.680790,0.199605,...,1.768025,0.743333,0.350988,0.269259,-36.753086,-0.469136,-17.876543,0.291654,0.098086,0.0
std,2.908215,0.214833,1.834677,1.519355,0.896734,2.390293,3.04885,72.095797,0.088962,0.084498,...,1.031010,0.676966,0.119610,0.162471,324.379081,5.886609,301.186752,0.203314,0.128330,0.0
min,3.000000,0.000000,1.200000,0.200000,1.300000,1.800000,1.00000,225.000000,0.410000,0.052000,...,0.760000,0.230000,0.100000,0.060000,-1172.000000,-16.000000,-797.000000,0.000000,0.000000,0.0
25%,6.000000,0.333000,2.400000,1.200000,2.400000,4.900000,5.70000,320.000000,0.623000,0.135000,...,1.100000,0.380000,0.250000,0.160000,-207.000000,-4.000000,-183.000000,0.143000,0.000000,0.0
50%,8.000000,0.500000,3.400000,2.500000,2.900000,6.200000,7.90000,385.000000,0.691000,0.215000,...,1.350000,0.450000,0.370000,0.190000,-3.000000,0.000000,6.000000,0.250000,0.077000,0.0
75%,10.000000,0.615000,4.400000,3.900000,3.300000,8.300000,8.90000,416.000000,0.751000,0.275000,...,1.700000,0.530000,0.430000,0.380000,159.000000,3.000000,147.000000,0.444000,0.143000,0.0
max,14.000000,0.875000,9.300000,5.600000,5.600000,12.400000,10.50000,486.000000,0.849000,0.337000,...,4.250000,2.430000,0.590000,0.670000,741.000000,10.000000,749.000000,0.800000,0.600000,0.0